### ISSUE TITLE
import failing: ModuleNotFoundError: No module named 'urbisphereAtmOapi.post'

### ISSUE THREAD

**Issue by kitbenjamin** [Urban-Meteorology-Reading/urbisphereAtmOapi#5]
```
(urbisphere) C:\Users\kitbe>pip install git+https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi.git

Collecting git+https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi.git
  Cloning https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi.git to c:\users\kitbe\appdata\local\temp\pip-req-build-3z_dfvus
  Running command git clone -q https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi.git 'C:\Users\kitbe\AppData\Local\Temp\pip-req-build-3z_dfvus'
Building wheels for collected packages: urbisphereAtmOapi
  Building wheel for urbisphereAtmOapi (setup.py) ... done
  Created wheel for urbisphereAtmOapi: filename=urbisphereAtmOapi-0.1-py3-none-any.whl size=4049 sha256=89e0c8d0c514a535b678c4168e7aa897ccbc7408d47c40e79e0dabac98f1d556
  Stored in directory: C:\Users\kitbe\AppData\Local\Temp\pip-ephem-wheel-cache-eqbi223v\wheels\6d\6f\85\a0b176e55732acd78df52846bda41a09a7c87f6c58457b0c4b
Successfully built urbisphereAtmOapi
Installing collected packages: urbisphereAtmOapi
Successfully installed urbisphereAtmOapi-0.1
```

```
(urbisphere) C:\Users\kitbe>python
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import urbisphereAtmOapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kitbe\anaconda3\envs\urbisphere\lib\site-packages\urbisphereAtmOapi\__init__.py", line 4, in <module>
    from urbisphereAtmOapi.obsdata import ObsData
  File "C:\Users\kitbe\anaconda3\envs\urbisphere\lib\site-packages\urbisphereAtmOapi\obsdata.py", line 1, in <module>
    import urbisphereAtmOapi.post as post
ModuleNotFoundError: No module named 'urbisphereAtmOapi.post'
>>>
```

**Comment by willmorrison1** [comment]
@kitbenjamin try 

```pip install git+https://github.com/Urban-Meteorology-Reading/urbisphereAtmOapi.git@fix-package-build```

**Comment by kitbenjamin** [comment]
Thanks thats done the job. I'll merge and delete the branch.
